# Utiliser l'image officielle PHP avec Apache
FROM php:8.2-apache

# Installer les extensions PHP nécessaires
RUN docker-php-ext-install mysqli pdo pdo_mysql

# Activer le mod_rewrite pour Apache
RUN a2enmod rewrite

# Copier les fichiers du site dans le dossier par défaut d'Apache
COPY . /var/www/html/

# Exposer le port 80
EXPOSE 80
